=== ZhargalTor/JavaTechnologi/Chapter 15/15/flatware.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="FlatWare">

        <xs:complexType>
            <xs:sequence>

                <xs:element name="Item" maxOccurs="unbounded">

                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="Type" type="xs:string"/>
                            <xs:element name="Origin" type="xs:string"/>

                            <xs:element name="Visual">

                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="BladeLength"
                                                    type="xs:int"
                                                    minOccurs="0"/>

                                        <xs:element name="ToothLength"
                                                    type="xs:int"
                                                    minOccurs="0"/>

                                        <xs:element name="BladeWidth"
                                                    type="xs:int"/>

                                        <xs:element name="Material"
                                                    type="xs:string"/>

                                        <xs:element name="Handle">

                                            <xs:complexType mixed="true">
                                                <xs:simpleContent>

                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="type"
                                                                      type="xs:string"
                                                                      use="required"/>
                                                    </xs:extension>

                                                </xs:simpleContent>
                                            </xs:complexType>

                                        </xs:element>

                                    </xs:sequence>
                                </xs:complexType>

                            </xs:element>

                            <xs:element name="Value"
                                        type="xs:boolean"/>

                        </xs:sequence>
                    </xs:complexType>

                </xs:element>

            </xs:sequence>
        </xs:complexType>

    </xs:element>

</xs:schema>

=== ZhargalTor/JavaTechnologi/Chapter 15/15/flatware.xml
<?xml version="1.0" encoding="UTF-8"?>

<FlatWare xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="flatware.xsd">

    <Item>
        <Type>Нож</Type>
        <Origin>Германия</Origin>

        <Visual>
            <BladeLength>20</BladeLength>
            <BladeWidth>30</BladeWidth>
            <Material>Сталь</Material>
            <Handle type="wood">Дуб</Handle>
        </Visual>

        <Value>true</Value>
    </Item>

    <Item>
        <Type>Вилка</Type>
        <Origin>Франция</Origin>

        <Visual>
            <ToothLength>15</ToothLength>
            <BladeWidth>20</BladeWidth>
            <Material>Сталь</Material>
            <Handle type="metal">Металл</Handle>
        </Visual>

        <Value>false</Value>
    </Item>

    <Item>
        <Type>Ложка</Type>
        <Origin>Италия</Origin>

        <Visual>
            <BladeLength>12</BladeLength>
            <BladeWidth>25</BladeWidth>
            <Material>Медь</Material>
            <Handle type="plastic">Пластик</Handle>
        </Visual>

        <Value>true</Value>
    </Item>

</FlatWare>
